# Generated by Django 5.2.8 on 2025-11-26 15:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0027_registrocondiciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ruc_dni', models.CharField(max_length=15, unique=True, verbose_name='RUC / DNI')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_cliente', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista')], default='MAYORISTA', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('toneladas_solicitadas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toneladas solicitadas')),
                ('precio_unitario_ton', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por tonelada (S/.)')),
                ('total_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DESPACHADO', 'Despachado')], default='PENDIENTE', max_length=15)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('tipo_venta', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA_POS', 'Minorista - Punto de Venta'), ('MINORISTA_PEDIDO', 'Minorista - Pedido')], default='MAYORISTA', editable=False, max_length=20)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mayoristas_aprobados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_mayoristas', to='comercializacion.cliente')),
                ('lote', models.ForeignKey(limit_choices_to={'activo': True, 'etapa_actual': 'ENGORDE'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_mayoristas', to='produccion.lote', verbose_name='Lote (Engorde)')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del producto')),
                ('cantidad_ton', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (ton)')),
                ('precio_unitario_ton', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario (S/.)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercializacion.pedidomayorista')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_venta', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA_POS', 'Minorista - Punto de Venta'), ('MINORISTA_PEDIDO', 'Minorista - Pedido')], max_length=20)),
                ('total_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercializacion.cliente')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.lote')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaMinoristaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('PREPARADO', 'Preparado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='REGISTRADO', max_length=15)),
                ('tipo_venta', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA_POS', 'Minorista - Punto de Venta'), ('MINORISTA_PEDIDO', 'Minorista - Pedido')], default='MINORISTA_PEDIDO', editable=False, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercializacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(limit_choices_to={'activo': True, 'etapa_actual': 'ENGORDE'}, on_delete=django.db.models.deletion.PROTECT, to='produccion.lote', verbose_name='Lote (Engorde)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('precio_unitario_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario (S/.)')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercializacion.ventaminoristapedido')),
            ],
        ),
        migrations.CreateModel(
            name='VentaMinoristaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('tipo_venta', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA_POS', 'Minorista - Punto de Venta'), ('MINORISTA_PEDIDO', 'Minorista - Pedido')], default='MINORISTA_POS', editable=False, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercializacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(limit_choices_to={'activo': True, 'etapa_actual': 'ENGORDE'}, on_delete=django.db.models.deletion.PROTECT, to='produccion.lote', verbose_name='Lote (Engorde)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('precio_unitario_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario (S/.)')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercializacion.ventaminoristapos')),
            ],
        ),
    ]
