# Generated by Django 5.2.6 on 2025-09-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_preguntaseguridad_customuser_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
    ]
