# Generated by Django 5.2.6 on 2025-09-10 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima_biomasa', models.FloatField(help_text='En kilogramos (kg)')),
                ('esta_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bastidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: BAST-2409-01', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima_biomasa', models.FloatField(help_text='En kilogramos (kg)')),
                ('esta_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima_biomasa', models.FloatField(help_text='En kilogramos (kg)')),
                ('esta_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('etapa_actual', models.CharField(choices=[('OVAS', 'Ovas'), ('ALEVINES', 'Alevines'), ('ENGORDE', 'Engorde')], max_length=10)),
                ('cantidad_total_peces', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso_etapa', models.DateField(auto_now_add=True)),
                ('peso_promedio_pez_gr', models.FloatField(default=0.0)),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('artesa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_actual', to='produccion.artesa')),
                ('bastidor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_actual', to='produccion.bastidor')),
                ('jaula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote_actual', to='produccion.jaula')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('alimentacion_realizada', models.BooleanField(default=False)),
                ('limpieza_realizada', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.lote')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.lote')),
            ],
        ),
    ]
