# Generated by Django 5.2.6 on 2025-09-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bastidor',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_promedio_pez_gr',
            field=models.FloatField(default=0.0, help_text='Peso promedio en gramos'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_alimento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='produccion.lote'),
        ),
        migrations.AlterField(
            model_name='registromortalidad',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_mortalidad', to='produccion.lote'),
        ),
    ]
