# Generated by Django 5.2.6 on 2025-09-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_bastidor_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='bastidor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='artesa',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='bastidor',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
