# Generated by Django 5.2.6 on 2025-09-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_remove_artesa_nombre_remove_bastidor_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='capacidad_maxima_biomasa',
        ),
        migrations.RemoveField(
            model_name='bastidor',
            name='capacidad_maxima_biomasa',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='capacidad_maxima_biomasa',
        ),
        migrations.AddField(
            model_name='artesa',
            name='capacidad_maxima_unidades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bastidor',
            name='capacidad_maxima_unidades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jaula',
            name='capacidad_maxima_unidades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo_lote',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
