# Generated by Django 5.2.6 on 2025-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_remove_artesa_capacidad_maxima_biomasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_alimento_diario',
            field=models.FloatField(default=0.0, help_text='Cantidad de alimento a dar por día (en kg)'),
        ),
        migrations.AlterField(
            model_name='artesa',
            name='capacidad_maxima_unidades',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima en unidades de alevines'),
        ),
        migrations.AlterField(
            model_name='bastidor',
            name='capacidad_maxima_unidades',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima en unidades de ovas'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='capacidad_maxima_unidades',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima en unidades de peces'),
        ),
    ]
