# Generated by Django 5.2.6 on 2025-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_lote_cantidad_alimento_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesa',
            name='tipo',
            field=models.CharField(choices=[('PE', 'Pequeña (8-10 cm)'), ('ME', 'Mediana (10-12 cm)'), ('GR', 'Grande (12-14 cm)')], default='PE', max_length=2),
        ),
    ]
