# Generated by Django 5.2.6 on 2025-09-11 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_artesa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_ingreso_etapa',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
