# Generated by Django 5.2.6 on 2025-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_alter_lote_fecha_ingreso_etapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='artesa',
            name='talla_max_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla Máxima (cm)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='talla_min_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla Mínima (cm)'),
        ),
    ]
