# Generated by Django 5.2.6 on 2025-09-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_remove_artesa_tipo_artesa_talla_max_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='talla_max_cm',
        ),
        migrations.RemoveField(
            model_name='artesa',
            name='talla_min_cm',
        ),
        migrations.AddField(
            model_name='lote',
            name='talla_max_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla Máxima (cm)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='talla_min_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla Mínima (cm)'),
        ),
    ]
