# Generated by Django 5.2.6 on 2025-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_remove_artesa_talla_max_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='peso_promedio_pez_gr',
            field=models.FloatField(blank=True, help_text='Peso promedio en gramos', null=True),
        ),
    ]
