# Generated by Django 5.2.6 on 2025-09-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_alter_lote_peso_promedio_pez_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesa',
            name='talla_max_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla Máxima (cm)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='talla_min_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Talla Mínima (cm)'),
        ),
    ]
