# Generated by Django 5.2.6 on 2025-09-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_artesa_talla_max_cm_artesa_talla_min_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='cantidad_alimento_diario',
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad_alimento_diario_gr',
            field=models.FloatField(default=0.0, help_text='Cantidad de alimento a dar por día (en GRAMOS)'),
        ),
    ]
