# Generated by Django 5.2.6 on 2025-09-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_remove_lote_cantidad_alimento_diario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='talla_max_cm',
        ),
        migrations.RemoveField(
            model_name='artesa',
            name='talla_min_cm',
        ),
    ]
