# Generated by Django 5.2.7 on 2025-10-13 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_remove_artesa_talla_max_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('cantidad_alimento_gr', models.FloatField(help_text='Cantidad de alimento administrado en gramos')),
                ('tipo_alimento', models.CharField(help_text='Tipo de alimento utilizado', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la alimentación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_alimentacion', to='produccion.lote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Alimentación',
                'verbose_name_plural': 'Registros de Alimentación',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
