# Generated by Django 5.2.6 on 2025-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_remove_artesa_talla_max_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaula',
            name='tipo',
            field=models.CharField(choices=[('JUVENIL', 'Juvenil'), ('ENGORDE', 'Engorde')], default='ENGORDE', max_length=10, verbose_name='Tipo de Jaula'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='etapa_actual',
            field=models.CharField(choices=[('OVAS', 'Ovas'), ('ALEVINES', 'Alevines'), ('JUVENILES', 'Juveniles'), ('ENGORDE', 'Engorde')], max_length=10),
        ),
    ]
