# Generated by Django 5.1 on 2025-10-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_jaula_tipo_alter_lote_etapa_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='capacidad_maxima_unidades',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='capacidad_maxima_unidades',
        ),
        migrations.AddField(
            model_name='artesa',
            name='alto_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Alto / Profundidad (m)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='ancho_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='apotema_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Apotema (m)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='capacidad_maxima_kg',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Capacidad Máxima de Biomasa (kg)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='densidad_siembra_kg_m3',
            field=models.FloatField(default=15.0, help_text='Baja (2-15), Media (15-30), Súper Intensiva (>50)', verbose_name='Densidad de Siembra (kg/m³)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='forma',
            field=models.CharField(choices=[('RECTANGULAR', 'Rectangular'), ('CIRCULAR', 'Circular'), ('HEXAGONAL', 'Hexagonal'), ('DECAGONAL', 'Decagonal')], default='RECTANGULAR', max_length=20, verbose_name='Forma de la unidad'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='lado_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Lado (m)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='largo_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Largo (m)'),
        ),
        migrations.AddField(
            model_name='artesa',
            name='radio_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Radio (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='alto_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Alto / Profundidad (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='ancho_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='apotema_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Apotema (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='capacidad_maxima_kg',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Capacidad Máxima de Biomasa (kg)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='densidad_siembra_kg_m3',
            field=models.FloatField(default=15.0, help_text='Baja (2-15), Media (15-30), Súper Intensiva (>50)', verbose_name='Densidad de Siembra (kg/m³)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='forma',
            field=models.CharField(choices=[('RECTANGULAR', 'Rectangular'), ('CIRCULAR', 'Circular'), ('HEXAGONAL', 'Hexagonal'), ('DECAGONAL', 'Decagonal')], default='RECTANGULAR', max_length=20, verbose_name='Forma de la unidad'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='lado_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Lado (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='largo_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Largo (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='radio_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Radio (m)'),
        ),
        migrations.AlterField(
            model_name='artesa',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bastidor',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
