# Generated by Django 5.1 on 2025-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_remove_artesa_capacidad_maxima_unidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='apotema_m',
        ),
        migrations.RemoveField(
            model_name='artesa',
            name='radio_m',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='apotema_m',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='radio_m',
        ),
        migrations.AddField(
            model_name='artesa',
            name='diametro_m',
            field=models.FloatField(blank=True, help_text='Para formas circulares o poligonales, es la distancia de lado a lado.', null=True, verbose_name='Diámetro / Ancho (m)'),
        ),
        migrations.AddField(
            model_name='jaula',
            name='diametro_m',
            field=models.FloatField(blank=True, help_text='Para formas circulares o poligonales, es la distancia de lado a lado.', null=True, verbose_name='Diámetro / Ancho (m)'),
        ),
        migrations.AlterField(
            model_name='artesa',
            name='alto_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura del Agua / Profundidad Efectiva (m)'),
        ),
        migrations.AlterField(
            model_name='artesa',
            name='densidad_siembra_kg_m3',
            field=models.FloatField(default=10.0, help_text='Baja (2-15), Media (15-30), Súper Intensiva (>50)', verbose_name='Densidad de Siembra (kg/m³)'),
        ),
        migrations.AlterField(
            model_name='artesa',
            name='lado_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud de un lado (m)'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='alto_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura del Agua / Profundidad Efectiva (m)'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='densidad_siembra_kg_m3',
            field=models.FloatField(default=10.0, help_text='Baja (2-15), Media (15-30), Súper Intensiva (>50)', verbose_name='Densidad de Siembra (kg/m³)'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='lado_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud de un lado (m)'),
        ),
    ]
