# Generated by Django 5.1 on 2025-10-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_remove_artesa_apotema_m_remove_artesa_radio_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artesa',
            name='esta_disponible',
        ),
        migrations.RemoveField(
            model_name='jaula',
            name='esta_disponible',
        ),
        migrations.AlterField(
            model_name='lote',
            name='artesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='produccion.artesa'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='jaula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='produccion.jaula'),
        ),
    ]
