# Generated by Django 5.1 on 2025-10-12 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_remove_artesa_esta_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='cantidad_alimento_diario_gr',
        ),
        migrations.AlterField(
            model_name='artesa',
            name='capacidad_maxima_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Capacidad Máxima de Biomasa (kg)'),
        ),
        migrations.AlterField(
            model_name='artesa',
            name='densidad_siembra_kg_m3',
            field=models.FloatField(default=10.0, verbose_name='Densidad de Siembra (kg/m³)'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='capacidad_maxima_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Capacidad Máxima de Biomasa (kg)'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='densidad_siembra_kg_m3',
            field=models.FloatField(default=10.0, verbose_name='Densidad de Siembra (kg/m³)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_promedio_pez_gr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso promedio en gramos', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='talla_max_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla Máxima (cm)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='talla_min_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla Mínima (cm)'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
