# Generated by Django 5.1 on 2025-10-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0019_remove_lote_cantidad_alimento_diario_gr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artesa',
            name='lado_m',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Longitud de Lado (calculado)'),
        ),
        migrations.AlterField(
            model_name='jaula',
            name='lado_m',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Longitud de Lado (calculado)'),
        ),
    ]
