# Generated by Django 5.2.6 on 2025-10-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_alter_artesa_lado_m_alter_jaula_lado_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='tipo_alimento',
        ),
    ]
