# Generated by Django 5.1 on 2025-10-13 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0021_remove_lote_tipo_alimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_movimiento', models.CharField(choices=[('CREACION', 'Creación de Lote'), ('MOVIMIENTO', 'Movimiento entre Unidades'), ('BAJAS', 'Registro de Mortalidad'), ('MEDICION', 'Registro de Talla/Peso'), ('FINALIZADO', 'Lote Finalizado')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad_afectada', models.IntegerField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='produccion.lote')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
