# Generated by Django 5.1 on 2025-10-13 06:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0022_historialmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_inicial',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cantidad de peces al inicio de la etapa actual'),
        ),
        migrations.AddField(
            model_name='lote',
            name='peso_promedio_inicial_gr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Peso promedio al inicio de la etapa actual', max_digits=7),
        ),
    ]
