# Generated by Django 5.1 on 2025-10-15 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('produccion', '0023_lote_cantidad_inicial_lote_peso_promedio_inicial_gr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('biomasa_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_peces', models.PositiveIntegerField(default=0)),
                ('alimento_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('mortalidad_total', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('content_type', 'object_id', 'fecha')},
            },
        ),
    ]
