# Generated by Django 5.1 on 2025-10-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0024_registrounidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción y Síntomas')),
                ('tratamiento', models.TextField(help_text='Pasos recomendados para el tratamiento.')),
                ('prevencion', models.TextField(help_text='Medidas para prevenir la enfermedad.')),
            ],
        ),
    ]
