# Generated by Django 5.2.6 on 2025-10-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0025_enfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el lote está activo o ha sido finalizado/cerrado'),
        ),
    ]
