# Generated by Django 5.2.6 on 2025-10-15 22:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0026_lote_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('temp_agua_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura del Agua (°C)')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nivel de pH')),
                ('oxigeno_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Oxígeno Disuelto (mg/L)')),
                ('amoniaco_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amoníaco (mg/L)')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_condiciones', to='produccion.lote')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('lote', 'fecha')},
            },
        ),
    ]
