# Generated by Django 5.2.7 on 2025-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_proveedor_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='activo',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
